### ISSUE TITLE
Make Firefox version

### ISSUE THREAD

**Issue by makaroni4** [makaroni4/youtube_time_tracker#8]

**Comment by wanecek** [comment]
I tried running it as a Firefox extension as-is (only building it first), and it seems to run fine! (Wow, the web extension API cross-compatibility has come far :heart_eyes:)

For reference, to test the extension in Firefox, I went through the steps below

```bash
# After having run `npm install`...

npm run build
npx web-ext run -s ./extension --verbose
```

**Comment by makaroni4** [comment]
@wanecek thanks a lot for checking, I just submitted the extension to FF and it just worked 🍾 Thanks a lot 🍻 

Here's the URL: https://addons.mozilla.org/en-US/firefox/addon/youtube-time-tracker/

I see that images weren't added to Add On page and SVG icons are missing in FF, but it counts time correctly. I'll fix SVGs later 🙏
